name = "DHMMs"
uuid = "871b1990-e9db-4005-9c80-f6dd9624f7c1"
authors = ["Mateusz Kaduk <mateusz.kaduk@gmail.com>"]
version = "0.1.0"

[deps]
BioMarkovChains = "f861b655-cb5f-42ce-b66a-341b542d4f2c"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
HiddenMarkovModels = "84ca31d5-effc-45e0-bfda-5a68cd981f47"

[compat]
BioMarkovChains = "1.0.0"
BioSequences = "3.5.0"
Distributions = "0.25.122"
FASTX = "2.1.7"
HiddenMarkovModels = "0.7.0"
